export default [
  {
    id: 1,
    title: "Fylo Landing Page",
    brief: "",
    img: "/img/fylo.png",
    alt: "Fylo Landing Page screenshot",
    url: "https://avu0s.github.io/vrs-fylo-landing/",
    tools: ["React", "Sass", "Vite"],
  },
  {
    id: 2,
    title: "mPharma Landing Page",
    brief: "",
    img: "/img/pharma.png",
    alt: "mPharma Landing Page screenshot",
    url: "https://avu0s.github.io/mPharma/",
    tools: ["HTML", "Sass", "JS"],
  },
  {
    id: 3,
    title: "Animated Glass Classes",
    brief: "",
    img: "/img/agc.png",
    alt: "Animated Glass Classes screenshot",
    url: "https://avu0s.github.io/animated-glass-comps/",
    tools: ["HTML", "CSS"],
  },
  {
    id: 4,
    title: "Card Variants",
    brief: "",
    img: "/img/cards.png",
    alt: "Card Variants screenshot",
    url: "https://avu0s.github.io/Top-Cards/",
    tools: ["HTML", "CSS"],
  },
];
